id: P57513038
initial_creation_type: input
source_metadata:
  title: Swift Rebirth Prayers
  language: fr
  description: 'A selection of prayers for the swift rebirth (myur byon gsol ’debs)
    of prominent individuals (arranged alphabetically by subject):'
  volume:
    4c69fd4597c6485d838ed6a243271cff:
      title: 'The Swift Fulfilment of Wishes: A Prayer for the Swift Return of the
        Supreme Tulku of the Fifth Drubwang Dzogchen Rinpoche'
      parent: Fifth Dzogchen Rinpoche
    805e17a5e1f54eaa8fd719e4cfa0a707:
      title: Prayer for Swift Rebirth of the Fourth Dodrupchen Rinpoche
      parent: Fourth Dodrupchen Rinpoche
    1fd81493afd24ab991ac5839b5b6a695:
      title: Prayer for Swift Rebirth of the Fourth Dodrupchen Rinpoche, Tupten Trinlé
        Palzangpo
      parent: Fourth Dodrupchen Rinpoche
    7623be760df24ecf926d4c0d0cc334ca:
      title: Prayer for the Swift Rebirth of the Fourth Dodrupchen Rinpoche
      parent: Fourth Dodrupchen Rinpoche
    b4a978b9f30b46ba86f2039172a4a3c8:
      title: A Prayer for the Swift Return of the Fourth Kyabje Dodrupchen Rinpoche
      parent: Fourth Dodrupchen Rinpoche
    6e85586c021f4a7aac4a531a4cc841b2:
      title: 'The Moonlight of Auspiciousness: A Yearning Prayer to the Noble and
        Glorious Guru Combined with an Aspiration for His Swift Return'
      parent: Gyurme Tsewang Gyatso
    a579b8b79d77401b8d836fb085491763:
      title: Prayer to Kongtrul Yönten Gyatso
      parent: Jamgön Kongtrul Lodrö Thaye
    e6d5ac72eec94421aefd530251024880:
      title: Prayer for the Swift Rebirth of Jamyang Khyenrab Tayé
      parent: Jamyang Khyenrab Tayé
    7740a10acc0247c18ce3f5b44a38dc99:
      title: Lamenting Prayer to Jamyang Chökyi Lodrö
      parent: Jamyang Khyentse Chökyi Lodrö
    ab96b10c665a46d5854d5387f01af7ba:
      title: 'Wondrous Light of the Moon: A Prayer for the Swift Appearance of the
        Supreme Tulku of Vajradhara'
      parent: Jamyang Loter Wangpo
    d8c8b059432f4388be3f16050d04df6d:
      title: 'The Swift Fulfilment of Wishes: Prayer for the Swift Appearance of the
        Supreme Tulku of the Mañjughoṣa Guru'
      parent: Katok Situ Chökyi Gyatso
    d8e31da707c94463aba07c450a254ac8:
      title: 'Cymbals to Invoke a Compassionate Response: A Prayer for Swift Rebirth
        of Khandro Tsering Chödrön'
      parent: Khandro Tsering Chödrön
    ea43eba5b15b47beaff189bad435fdb0:
      title: 'The Swift Infusion of Blessings: A Lament and Prayer to Invoke the Wisdom
        Mind of Khenchen Vāgindra on the Occasion of His Passing into the Great Peace
        of the Dharmadhātu'
      parent: Ngawang Samten Lodrö
    cffc7f0962054439bde85b849837674d:
      title: A Prayer for the Swift Rebirth of Tenpai Nyima Rinpoche
      parent: Tenpai Nyima Rinpoche
    76bda0a54cdf4270874e2a88cc8f9a15:
      title: 'The Tambura of Devotion: A Prayer for the Swift Appearance of the Supreme
        Tulku of the All-Seeing Conqueror and Cardinal Guardian of the Land of Snows'
      parent: Thirteenth Dalai Lama
    abed2c4cc2a44384a3911f6dd9edec67:
      title: Prayer for the Swift Rebirth of Kyabjé Trulshik Rinpoche
      parent: Trulshik Rinpoche
created_at: '2022-03-01T05:59:59.957953'
last_modified_at: '2022-03-01T05:59:59.957956'
